export default [
    "Asunción"
    , "Concepción"
    , "Belén"
    , "Horqueta"
    , "Loreto"
    , "San Carlos del Apa"
    , "San Lázaro"
    , "Yby Ya'ú"
    , "Azotey"
    , "Sargento José Félix López"
    , "San Alfredo"
    , "Paso Barreto (Arroyito)"
    , "San Pedro del Ycuamandiyú"
    , "Antequera"
    , "Choré"
    , "General Elizardo Aquino"
    , "Itacurubí del Rosario"
    , "Lima"
    , "Nueva Germania"
    , "San Estanislao"
    , "San Pablo"
    , "Tacuatí"
    , "Unión"
    , "25 de Diciembre"
    , "Villa del Rosario"
    , " General Isidoro Resquín"
    , "Yataity del Norte"
    , "Guayaibí"
    , "Capiibary"
    , "Santa Rosa del Aguaray"
    , "Yrybucuá"
    , "Liberación"
    , "Caacupé"
    , "Altos"
    , "Arroyos y Esteros"
    , "Atyrá"
    , "Caraguatay"
    , "Emboscada"
    , "Eusebio Ayala"
    , "Isla Pucú"
    , "Itacurubí de la Cordillera"
    , "Juan de Mena"
    , "Loma Grande"
    , "Mbocayaty del Yhaguy"
    , "Nueva Colombia"
    , "Piribebuy"
    , "Primero de Marzo"
    , "San Bernardino"
    , "Santa Elena"
    , "Tobatí"
    , "Valenzuela"
    , "San José Obrero"
    , "Villarrica"
    , "Borja"
    , "Mauricio José Troche"
    , "Coronel Martínez"
    , "Félix Pérez Cardozo"
    , "General Eugenio A. Garay"
    , "Colonia Independencia"
    , "Itapé"
    , "Iturbe"
    , "José Fassardi"
    , "Mbocayaty"
    , "Natalicio Talavera"
    , "Ñumí"
    , "San Salvador"
    , "Yataity"
    , "Doctor Bottrell"
    , "Paso Yobái"
    , "Tebicuary"
    , "Coronel Oviedo"
    , "Caaguazú"
    , "Carayaó"
    , "Doctor Cecilio Báez"
    , "Santa Rosa del Mbutuy"
    , "Doctor Juan Manuel Frutos"
    , "Repatriación"
    , "Nueva Londres"
    , "San Joaquín"
    , "San José de los Arroyos"
    , "Yhú"
    , "Doctor J. Eulogio Estigarribia"
    , "R. I. Tres Corrales"
    , "Raúl Arsenio Oviedo"
    , "José Domingo Ocampos"
    , "Mariscal Francisco Solano López"
    , "La Pastora"
    , "3 de Febrero"
    , "Simón Bolívar"
    , "Vaquería"
    , "Tembiaporá"
    , "Nueva Toledo"
    , "Caazapá"
    , "Abaí"
    , "Buena Vista"
    , "Doctor Moisés S. Bertoni"
    , "General Higinio Morínigo"
    , "Maciel"
    , "San Juan Nepomuceno"
    , "Tavaí"
    , "Fulgencio Yegros"
    , "Yuty"
    , "3 de Mayo"
    , "Encarnacion"
    , "Bella Vista"
    , "Cambyreta"
    , "Capitan Meza"
    , "Capitan Miranda"
    , "Nueva Alborada"
    , "Carmen Del Parana"
    , "Coronel Bogado"
    , "Carlos Antonio Lopez"
    , "Natalio"
    , "Fram"
    , "General Artigas"
    , "General Delgado"
    , "Hohenau"
    , "Jesus"
    , "Leandro Oviedo"
    , "Obligado"
    , "Mayor Otaño"
    , "San Cosme Y Damian"
    , "San Pedro Del Parana"
    , "San Rafael Del Parana"
    , "Trinidad"
    , "Edelira"
    , "Tomas Romero Pereira"
    , "Alto Vera"
    , "La Paz"
    , "Yatytay"
    , "San Juan Del Parana"
    , "Pirapo"
    , "Itapua Poty"
    , "San Juan Bautista"
    , "Ayolas"
    , "San Ignacio"
    , "San Miguel"
    , "San Patricio"
    , "Santa Maria"
    , "Santa Rosa"
    , "Santiago"
    , "Villa Florida"
    , "Yabebyry"
    , "Paraguarí"
    , "Acahay"
    , "Caapucú"
    , "General Bernardino Caballero"
    , "Carapeguá"
    , "Escobar"
    , "La Colmena"
    , "Mbuyapey"
    , "Pirayú"
    , "Quiindy"
    , "Quyquyhó"
    , "San Roque González de Santa Cruz"
    , "Sapucai"
    , "Tebicuarymí"
    , "Yaguarón"
    , "Ybycui"
    , "Yvytimi"
    , "Ciudad del Este"
    , "Presidente Franco"
    , "Domingo Martínez de Irala"
    , "Doctor Juan León Mallorquín"
    , "Hernandarias"
    , "Itakyry"
    , "Juan Emilio O'Leary"
    , "Ñacunday"
    , "Yguazú"
    , "Los Cedrales"
    , "Minga Guazú"
    , "San Cristóbal"
    , "Santa Rita"
    , "Naranjal"
    , "Santa Rosa del Monday"
    , "Minga Porá"
    , "Mbaracayú"
    , "San Alberto"
    , "Iruña"
    , "Santa Fe del Paraná"
    , "Tavapy"
    , "Doctor Raúl Peña"
    , "Areguá"
    , "Capiatá"
    , "Fernando De La Mora"
    , "Guarambaré"
    , "Itá"
    , "Itauguá"
    , "Lambaré"
    , "Limpio"
    , "Luque"
    , "Mariano Roque Alonso"
    , "Nueva Italia"
    , "Ñemby"
    , "San Antonio"
    , "San Lorenzo"
    , "Villa Elisa"
    , "Villeta"
    , "Ypacaraí"
    , "Ypané"
    , "Julián Augusto Saldívar"
    , "Pilar"
    , "Alberdi"
    , "Cerrito"
    , "Desmochados"
    , "General José Eduvigis Díaz"
    , "Guazú Cuá"
    , "Humaitá"
    , "Isla Umbú"
    , "Los Laureles"
    , "Mayor José J. Martínez"
    , "Paso de Patria"
    , "San Juan Bautista del Ñeembucú"
    , "Tacuaras"
    , "Villa Franca"
    , "Villa Oliva"
    , "Villalbín"
    , "Pedro Juan Caballero"
    , "Bella Vista"
    , "Capitán Bado"
    , "Zanja Pytá"
    , "Karapaí"
    , "Salto del Guairá"
    , "Corpus Christi"
    , "Curuguaty"
    , "Villa Ygatimí"
    , "Itanará"
    , "Ypejhú"
    , "Genaral Francisco Caballero Álvarez"
    , "Katueté"
    , "La Paloma"
    , "Nueva Esperanza"
    , "Yasy Kañy"
    , "Ybyrarovaná"
    , "Yby Pytá"
    , "Benjamín Aceval"
    , "Puerto Pinasco"
    , "Villa Hayes"
    , "Nanawa"
    , "Doctor José Falcón"
    ,"Teniente Primero Manuel Irala Fernández"
    ,"Teniente Esteban Martínez"
    ,"General José María Bruguez"
    ,"Mariscal Estigarribia"
    ,"Filadelfia"
    ,"Loma Plata"
    ,"Fuerte Olimpo"
    ,"Puerto Casado"
    ,"Bahía Negra"
    ,"Capitán Carmelo Peralta"
]